### PR TITLE
Update of guide to reflect changes in our system

### PR DESCRIPTION
**Pull request by leland-creswell**
Included information about the CRITICAL importance of using the proper API server, along with a bunch of changes to language that were causing huge problems for people trying to use this guide.

I STRONGLY suggest someone on the team looks at the Korean version and updates it following this. Seriously.

@KunHwanAhn @Kimilhee

### CODE REVIEW

**Comment by leland-creswell** [comment]
@Kimilhee I will add additional steps to this guide to cover the "missing pieces" that forced @thanhphu to waste time on simple questions yesterday.

Some of the missing pieces include:
- What gateway/sensors to use for pushing data into something that can be viewed on the Thing+ dashboard - for example, humidityEmulator, etc... strings are NOT available to partners - they cannot know how to address the "gateway"/"device" via API, as well as the driverName. Without this information, they MUST ask us, since we do not say anything about this in our tutorials
 
- reqID / deviceID are NOT called "reqID" or "deviceID" in the UI. UI shows reqID as "ID", and deviceID is actually the GATEWAY ID - this is not shown anywhere, so it needs to be in the tutorial (and also API docs)

- The basic process of creating an emulator with sensors by UI and then using that to show your data on our dashboard is strange and we do not say anything about it in the guide. Guide should include information on showing how to use the UI to create a gateway that API can push data too, AS WELL AS how to directly create an emulator gateway with attached sensors. 

- Our API docs are *extremely* confusing - Gateway-sensors section is for creating gateways with sensors.. In some places we say "device", in some place we say "gateway" (everything should be gateway??) - I need to do a full re-edit of the API docs and will create another issue for that.

It seems we haven't had any time to make our guides and documentation more usable by other devs :(

**Comment by leland-creswell** [comment]
Reminder - we need to add information on how to use MQTT somewhere in this guide.. and in our API documentation. There is no mention on how MQTT should be used with the API for pushing sensor data and I have no idea about it so I cannot edit by myself.

**Comment by Kimilhee** [comment]
@leland-creswell 
I think you need to have meeting with dev members(maybe Ryu and me) to discuss above problems and have time to reduce the gap of different view of understanding our documentation.
So that we could review our API docs and talk about each topic case by case which you couldn't accept in our API documentation, and make a revision of documentation right on there.

**Comment by leland-creswell** [comment]
@thanhphu can this be closed?

**Comment by thanhphu** [comment]
Yes, after it has been merged

**Comment by leland-creswell** [comment]
@thanhphu shall we add a bit extra to cover the specific part August got hung up on from Friday?

**Comment by SeokRyu** [comment]
1. File : doc/GettingStarted_authToken.md 
 - This is the Japanese API server -> I think commercial server is more better without Japanese  

2. File : doc/GettingStarted_authToken.md 
 -  [Register a Thing+ service](https://iot.thingplus.net/#/register) -> write url instead link cause target server
 -

**Comment by thanhphu** [comment]
@leland-creswell I included that the same day

@SeokRyu please check again

**Pull request merged**
